### ISSUE TITLE
网易云歌单 歌曲中数量过大时，查看预览结果会出现闪退

### ISSUE THREAD

**Issue by xiaoheitan521** [Winnie0408/LocalMusicHelper#9]
目前两个歌单，一个500首，一个600首都会出现闪退，200首的正常～

**Comment by Winnie0408** [comment]
应该不是数量的问题，之前尝试的时候，2000首的歌单也还是可以的🤔
大概率是其他原因，如果有抛出异常的详细信息的话，可以一起传上来看看呢🧐

**Comment by xiaoheitan521** [comment]
> 应该不是数量的问题，之前尝试的时候，2000首的歌单也还是可以的🤔
> 大概率是其他原因，如果有抛出异常的详细信息的话，可以一起传上来看看呢🧐

这是今天崩溃和闪退的日志[]()https://www.123pan.com/s/L1tRVv-YaSkd.html
所有的都打包了，以及当时扫描音乐出现的崩溃
下面的是歌单崩溃的～
`Process: com.hwinzniej.musichelper
PID: 11301
UID: 10388
Frozen: false
Flags: 0x20c8be44
Package: com.hwinzniej.musichelper v66 (1.5.2)
Foreground: Yes
Process-Runtime: 24969
Build: Xiaomi/houji/houji:14/UKQ1.230804.001/V816.0.45.0.UNCCNXM:user/release-keys
Crash-Handler: com.android.internal.os.RuntimeInit$KillApplicationHandler
Loading-Progress: 1.0
Dropped-Count: 0

android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
	at android.database.AbstractCursor.checkPosition(AbstractCursor.java:521)
	at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:139)
	at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:53)
	at com.hwinzniej.musichelper.activity.ConvertPage$previewResult$1.invokeSuspend(ConvertPage.kt:2888)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e6834d8, Dispatchers.IO]
`

**Comment by Winnie0408** [comment]
用的是在线获取歌单，还是读取数据库文件呢？

**Comment by xiaoheitan521** [comment]
> 用的是在线获取歌单，还是读取数据库文件呢？

读取数据库文件

**Comment by Winnie0408** [comment]
> > 用的是在线获取歌单，还是读取数据库文件呢？
> 
> 读取数据库文件

500和600多首的这两个歌单，在网易云里完整加载过吗？

**Comment by xiaoheitan521** [comment]
> > > 用的是在线获取歌单，还是读取数据库文件呢？
> > 
> > 读取数据库文件
> 
> 500和600多首的这两个歌单，在网易云里完整加载过吗？

测试了就是这个原因 感谢开发者🌹

**Comment by Winnie0408** [comment]
感谢反馈！后续会加个提示呢~🥰
